module.exports = [
    {
        cloth_id: 1,
        icon: 'T-shirt.png',
        color: "White",
        category: "T-shirt",
        type: "Top",
        dirty: false,
    },
    {
        cloth_id: 2,                
        icon: 'Shirt.png',
        color: "Red",
        category: "Shirt",
        type: "Top",
        dirty: true,
    },
    {
        cloth_id: 3,
        icon: 'Pants.png',
        color: "Green",
        category: "Pants",
        type: "Bottom",
        dirty: false,
    },
    {
        cloth_id: 4,        
        icon: 'Shorts.png',
        color: "Yellow",
        category: "Shorts",
        type: "Bottom",
        dirty: true,
    },
    {
        cloth_id: 5,
        icon: 'Longsleeve.png',
        color: "Grey",
        category: "Longsleeve",
        type: "Top",
        dirty: false,
    },
    {
        cloth_id: 6,
        icon: 'Skirt.png',
        color: "Blue",
        category: "Skirt",
        type: "Bottom",
        dirty: true,
    },
]